version: '3.7'
services:
  kusama:
    container_name: kusama-etl
    build: ./
    ports:
      - 4468:4468
    environment:
      PORT: 4468
      MAX_LAG: 1
      NETWORK: kusama
      PRISMA_ENDPOINT: http://prisma:4466
      ARCHIVE_NODE_ENDPOINT: wss://kusama-rpc.polkadot.io
  polkadot:
    container_name: polkadot-etl
    build: ./
    ports:
      - 4467:4467
    environment:
      PORT: 4467
      MAX_LAG: 1
      NETWORK: polkadot
      PRISMA_ENDPOINT: http://prisma:4466
      ARCHIVE_NODE_ENDPOINT: wss://rpc.polkadot.io
  prisma:
    container_name: prisma
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ${PRISMA_PG_HOST}
            user: ${PRISMA_PG_USER}
            password: ${PRISMA_PG_PASSWORD}
            rawAccess: true
            port: ${PRISMA_PG_PORT}
            migrations: true

